# 属性
name: test
age: 18

# 拼接
content: "name: ${name}, age: ${age}"

# 对象student前缀 ss
ss:
  name: test
  age: 18

# Server
server:
  port: 1000
  servlet:
    context-path: /

# Spring
spring:
  # 连接池配置, spring boot 2.0默认hikariCP, pom.xml中不需额外添加依赖
  datasource:
    # 新路径 com.mysql.cj.jdbc.Driver
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://116.62.198.241:3306/hrhbbx?serverTimezone=UTC&useSSL=false&useUnicode=true&characterEncoding=utf-8
    username: root
    password: Ak902078.
#    type: com.alibaba.druid.pool.DruidDataSource
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 5
      maximum-pool-size: 15
      auto-commit: true
      idle-timeout: 30000
      pool-name: hikariDataSource
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1

# 日志
logging:
  level:
    # 控制台打印SQL, 路径是Mapper接口所在的包
    com.springboot2.helloworld.dao: DEBUG
    # 控制日志输出级别
    root: info

# mybatis配置
mybatis:
  # 配置实体类所在包名
  type-aliases-package: com.springboot2.base.domain
  # 配置mapper xml文件所在路径，这里是一个数组
  mapper-locations: classpath:mapper/*.xml

# 分页配置
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql
